// <auto-generated />
using FeedbackApp.Data;
using FeedbackApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FeedbackApp.Migrations
{
    [DbContext(typeof(FeedbackContext))]
    [Migration("20180526185735_InitialSchema")]
    partial class InitialSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FeedbackApp.Models.Condition", b =>
                {
                    b.Property<int>("ConditionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Answer");

                    b.Property<int?>("FeedbackId");

                    b.Property<int>("QuestionId");

                    b.HasKey("ConditionId");

                    b.HasIndex("FeedbackId");

                    b.ToTable("condition");
                });

            modelBuilder.Entity("FeedbackApp.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Priority");

                    b.Property<Guid>("SurveyId");

                    b.Property<string>("Text");

                    b.HasKey("FeedbackId");

                    b.HasIndex("SurveyId");

                    b.ToTable("feedback");
                });

            modelBuilder.Entity("FeedbackApp.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Answer");

                    b.Property<Guid?>("SurveyId");

                    b.Property<string>("Text");

                    b.HasKey("QuestionId");

                    b.HasIndex("SurveyId");

                    b.ToTable("question");
                });

            modelBuilder.Entity("FeedbackApp.Models.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("survey");
                });

            modelBuilder.Entity("FeedbackApp.Models.Condition", b =>
                {
                    b.HasOne("FeedbackApp.Models.Feedback")
                        .WithMany("Conditions")
                        .HasForeignKey("FeedbackId");
                });

            modelBuilder.Entity("FeedbackApp.Models.Feedback", b =>
                {
                    b.HasOne("FeedbackApp.Models.Survey")
                        .WithMany("Feedback")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FeedbackApp.Models.Question", b =>
                {
                    b.HasOne("FeedbackApp.Models.Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId");
                });
#pragma warning restore 612, 618
        }
    }
}
